# Run this compose file to build jenkins/Dockerfile and deploy
# docker-compose run -e JENKINS_DOMCOM=jenkins.example.com -e NFS_SERVER=10.10.10.15 -e DTR_DOMCOM=dtr.example.com ... 
version: "3.3"
services:
  jenkins:
    build: jenkins
    #image: dtr.domain.com/apps/jenkins
    ports:
      - "8080"
    networks:
      - ucp-hrm
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # labels for interlock (docker 2.0)
        com.docker.lb.hosts: jenkins.apps.domain.com
        com.docker.lb.network: ucp-hrm
        com.docker.lb.port: "8080"
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
      - type: volume
        source: jenkins_build
        target: /var/jenkins_build
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
        read_only: true
      - type: bind
        source: /usr/bin/notary
        target: /usr/bin/notary
        read_only: true
      

# HTTP Routing Mesh Network in Docker EE 
networks:
  ucp-hrm:
    external: true

# NFS mount to persist jenkins home
volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw
      device: ":/nfs/jenkins_home"

# NFS mount to persist jenkins' build directory
  jenkins_build:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw
      device: ":/nfs/jenkins_build"
